# Generated by Django 3.1.7 on 2021-04-08 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_apps', '0002_food_food_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
