# Generated by Django 3.1.7 on 2021-06-29 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeuser',
            name='profile_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
